### ISSUE TITLE
Effect of optional chaining operator on function call

### ISSUE THREAD

**Issue by 1316346949** [tc39/proposal-optional-chaining#125] opened 2019-10-14 10:02 UTC
a?.()   ->     typeof a === 'function'  ? a() : undefined

**Comment by jazeee** [comment] 2019-10-14 13:42
Could you update the title to be more descriptive.
`this effect` -> something like `optional chaining function should test for typeof function`. This makes the issue page more reasonable to understand:
https://github.com/tc39/proposal-optional-chaining/issues

In any case, I could see this feature as desirable, and pretty ergonomic. I don't know if the maintainers of optional chaining proposal would find it to fit within the intention of the proposal.
It does feel somewhat edge case though, since one should write code to ensure that something is of type function vs other type like string.
Ie, it seems unusual to have code that could declare between `a = function...` and `a = 1234`. This seems like it would be a bigger problem in the codebase, which should probably be addressed in other ways...

**Comment by claudepache** [comment] 2019-10-14 14:05
> @1316346949 1316346949
> a?.() -> typeof a === 'function' ? a() : undefined

No, by design we have: a?.() -> a != null ? a() : undefined

That means that `a?.()` will throw a TypeError if `a` is neither nullish, nor callable.

See [the FAQ](https://github.com/tc39/proposal-optional-chaining#faq), item “Why does foo?.() throw when foo is neither nullish nor callable?”.

-----

> @jazeee
> In any case, I could see this feature as desirable, and pretty ergonomic. I don't know if the maintainers of optional chaining proposal would find it to fit within the intention of the proposal.

At this stage, it is too late to change the design of optional chaining (unless there is a major flaw).

**Comment by 1316346949** [comment] 2019-10-15 01:59
> > @1316346949 1316346949
> > a?.() -> typeof a === 'function' ? a() : undefined
> 
> No, by design we have: a?.() -> a != null ? a() : undefined
> 
> That means that `a?.()` will throw a TypeError if `a` is neither nullish, nor callable.
> 
> See [the FAQ](https://github.com/tc39/proposal-optional-chaining#faq), item “Why does foo?.() throw when foo is neither nullish nor callable?”.
> 
> > @jazeee
> > In any case, I could see this feature as desirable, and pretty ergonomic. I don't know if the maintainers of optional chaining proposal would find it to fit within the intention of the proposal.
> 
> At this stage, it is too late to change the design of optional chaining (unless there is a major flaw).

Thank you

**Comment by claudepache** [comment] 2019-10-16 12:47
Closing as Working as intended.

**Closed by claudepache** 2019-10-16 12:47 UTC
