### ISSUE TITLE
Optional chaining + private properties

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/proposal-optional-chaining#38] opened 2017-10-11 00:21 UTC
Private properties are statically resoled so `a?.#b` should be an early Syntax Error

Previous discussion https://github.com/tc39/proposal-private-fields/issues/78

**Comment by claudepache** [comment] 2017-10-11 05:10
In `a?.#b`, it is not statically known whether `a` is an object of the current class or null, so it makes sense to support that.

Closing as duplicate of #28

**Closed by claudepache** 2017-10-11 05:10 UTC
